### ISSUE TITLE
DDM : subdescriptor

### ISSUE THREAD

**Issue by awilkins** [MarkusAmshove/natls#506]
DDMs identify both superdescriptor and subdescriptor with `S` and the "SOURCE FIELDS" comment block

- Fields that are named elsewhere in the DDM make it a superdescriptor
- Fields that are NOT named elsewhere in the DDM make it a subdescriptor

e.g. when you suffix your box IDs with a letter indicating their size so you can query just for large boxes

```
  1 AE BOX-ID-SIZE                A    6  N S
*      -------- SOURCE FIELD(S) -------
*      BOX-ID(1-5)
*      BOX-SIZE(1-1)
```

Currently naming fields that do not exist elsewhere in the same DDM means the DDM doesn't parse.

(I think? All I see are 

"Could not resolve \<that DDM\>" in natlint or

"Trailing token \<IDENTIFIER\> not allowed here" in vscode

where it is referenced in views, but no error reports in the actual DDM in vscode / natlint).

**Comment by MarkusAmshove** [comment]
I did not know subdescriptors exist and can't really find documentation about them.

The diagnostic messages are weird because:

- Superdescriptors get parsed [here](https://github.com/MarkusAmshove/natls/blob/main/libs/natparse/src/main/java/org/amshove/natparse/parsing/ddm/DdmParser.java#L195) where the source fields comment is mandatory
  - Parsing Superdescriptors remembers child fields/ranges to reference them to fields later
https://github.com/MarkusAmshove/natls/blob/1a80a842f4e4ba8b39bd5de9e79548f657f340a6/libs/natparse/src/main/java/org/amshove/natparse/parsing/ddm/DdmParser.java#L204-L210
  - The fields then get resolved here which is where it most likely fails in your example
https://github.com/MarkusAmshove/natls/blob/1a80a842f4e4ba8b39bd5de9e79548f657f340a6/libs/natparse/src/main/java/org/amshove/natparse/parsing/ddm/DdmParser.java#L105-L116

The DDM parser is a port from a previous project which was all about code generation, meaning the exceptions don't get converted into nice diagnostics at the moment :-)

Is the type of subdescriptor fields derived from the descriptor itself?
Will `BOX-ID` be A5 and `BOX-SIZE` A1 ?

**Comment by MarkusAmshove** [comment]
How are the sub fields defined in VIEWs? 
These look like redefinitions on Adabas side, whereas we add REDEFINEs in our VIEWs

The generated "source fields" naming from predict also is confusing, as they are actually "target" fields in this case

**Comment by MarkusAmshove** [comment]
Did find the documentation: https://documentation.softwareag.com/adabas/ada701luw/basics/fdtrec.htm#fdtrecsub
Sorry for the spam :-)
